# Generated by Django 5.0.6 on 2024-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('vol', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'issues',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='issue',
            field=models.ManyToManyField(related_name='posts', to='articles.issue'),
        ),
    ]
