# Generated by Django 5.0.6 on 2024-06-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
