# Generated by Django 5.0.6 on 2024-06-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_author_email_author_fact_author_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='socials',
            field=models.CharField(default='LEFT_EMPTY', max_length=255),
        ),
    ]
