# Generated by Django 5.0.6 on 2024-06-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='Unknowable and Mysterious'),
        ),
        migrations.AlterField(
            model_name='author',
            name='roles',
            field=models.TextField(default='Staffwriter'),
        ),
    ]
