# Generated by Django 5.0.6 on 2024-06-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_author_alter_category_options_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
