# Generated by Django 5.0.6 on 2024-06-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_create_on_post_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'authors'},
        ),
    ]
