# Generated by Django 5.0.6 on 2024-06-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_issue_post_slug_post_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='vol',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='post',
            name='issue',
        ),
        migrations.AddField(
            model_name='post',
            name='issue',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.issue'),
            preserve_default=False,
        ),
    ]
