# Generated by Django 5.0.6 on 2024-06-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_post_issue_post_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='theme',
            new_name='name',
        ),
    ]
