# Generated by Django 5.0.6 on 2024-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='roles',
            field=models.TextField(default=':('),
            preserve_default=False,
        ),
    ]
