# Generated by Django 5.0.6 on 2024-06-17 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_delete_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='issues',
        ),
        migrations.AddField(
            model_name='post',
            name='issues',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='articles.issue'),
            preserve_default=False,
        ),
    ]
