# Generated by Django 5.0.6 on 2024-06-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.TextField(default='/static/author/anon.png'),
            preserve_default=False,
        ),
    ]
