# Generated by Django 5.0.6 on 2024-06-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_author_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(default='LEFT_EMPTY', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='fact',
            field=models.CharField(default='LEFT_EMPTY', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.CharField(default='LEFT_EMPTY', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='major',
            field=models.CharField(default='LEFT_EMPTY', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='pronouns',
            field=models.CharField(default='LEFT_EMPTY', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='year',
            field=models.CharField(default='LEFT_EMPTY', max_length=255),
        ),
    ]
