# Generated by Django 5.0.6 on 2024-08-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_post_published_alter_post_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Destination filename (include extension, like .png)'),
        ),
    ]
